<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>uuid</key>
        <string>2DBC95CE-20EC-4DBF-B555-BD2C44177FA4</string>
        <key>patterns</key>
        <array>
            <dict>
                <key>name</key>
                <string>keyword.command.icalObject</string>
                <!-- <string>keyword.command.icalObject</string> -->
                <key>match</key>
                <string>^(BEGIN|END)</string>
            </dict>
            <dict>
                <key>name</key>
                <string>constant.language.icalObjectType</string>
                <key>match</key>
                <string>:(VCALENDAR|VEVENT|VTODO|VJOURNAL|VFREEBUSY|VTIMEZONE|VALARM)$</string>
            </dict>
            <dict>
                <key>name</key>
                <string>constant.language.icalObjectType</string>
                <key>match</key>
                <string>:(DAYLIGHT|STANDARD)$</string>
            </dict>
            <dict>
                <key>name</key>
                <string>keyword.other.icalProperty</string>
                <key>match</key>
                <string>^(DTSTART|PRODID|VERSION|CALSCALE|METHOD)</string>
            </dict>
            <dict>
                <key>name</key>
                <string>keyword.other.icalProperty</string>
                <key>match</key>
                <string>^(DTEND|DTSTAMP|ORGANIZER|UID|CLASS|CREATED)</string>
            </dict>
            <dict>
                <key>name</key>
                <string>keyword.other.icalProperty</string>
                <key>match</key>
                <string>^(LOCATION|SEQUENCE|STATUS|SUMMARY|COMMENT)</string>
            </dict>
            <dict>
                <key>name</key>
                <string>keyword.other.icalProperty</string>
                <key>match</key>
                <string>^(TRANSP|ATTENDEE|ATTACH|FREEBUSY|METHOD|CONTACT)</string>
            </dict>
            <dict>
                <key>name</key>
                <string>keyword.other.icalProperty</string>
                <key>match</key>
                <string>^(DURATION|RRULE|EXDATE|EXRULE|URL|DESCRIPTION|ACTION)</string>
            </dict>
            <dict>
                <key>name</key>
                <string>keyword.other.icalProperty</string>
                <key>match</key>
                <string>^(LAST-MODIFIED|RECURRENCE-ID|TRIGGER|RELATED-TO|RDATE)</string>
            </dict>
            <dict>
                <key>name</key>
                <string>keyword.other.icalProperty</string>
                <key>match</key>
                <string>^(TZID|TZOFFSETFROM|TZOFFSETTO|TZNAME|TZURL)</string>
            </dict>
            <dict>
                <key>name</key>
                <string>keyword.other.icalProperty</string>
                <key>match</key>
                <string>^(PRIORITY|DUE|COMPLETED|PERCENT-COMPLETE|CATEGORIES)</string>
            </dict>
            <dict>
                <key>name</key>
                <string>keyword.other.icalProperty</string>
                <key>match</key>
                <string>^(RESOURCES|REPEAT|REQUEST-STATUS)</string>
            </dict>
            <dict>
                <key>name</key>
                <string>keyword.other.icalCustom</string>
                <key>match</key>
                <string>^X-[A-Z-]+</string>
            </dict>
            <dict>
                <key>name</key>
                <string>string.interpolated.icalDate</string>
                <key>match</key>
                <string>[0-9]{8}T[0-9]{6}Z?</string>
            </dict>
            <dict>
                <key>name</key>
                <string>variable.parameter.icalParameter</string>
                <key>match</key>
                <string>[A-Z0-9-]+=[^;:]+</string>
            </dict>
            <dict>
                <key>name</key>
                <string>constant.other.icalSetValue</string>
                <key>match</key>
                <string>(CONFIRMED|TENTATIVE|CANCELLED|DELEGATED|OPAQUE)</string>
            </dict>
            <dict>
                <key>name</key>
                <string>constant.other.icalSetValue</string>
                <key>match</key>
                <string>(NEEDS-ACTION|ACCEPTED|DECLINED|IN-PROGRESS)</string>
            </dict>
            <dict>
                <key>name</key>
                <string>constant.other.icalSetValue</string>
                <key>match</key>
                <string>(PRIVATE|PUBLIC|PUBLISH|GREGORIAN|DISPLAY)</string>
            </dict>
            <dict>
                <key>name</key>
                <string>constant.other.icalSetValue</string>
                <key>match</key>
                <string>:COMPLETED$</string>
            </dict>
        </array>
        <key>name</key>
        <string>iCalendar</string>
        <key>scopeName</key>
        <string>source.iCalendar</string>
        <key>fileTypes</key>
        <array>
            <string>ical</string>
            <string>ics</string>
            <string>ifb</string>
            <string>icalendar</string>
        </array>
    </dict>
</plist>